### ISSUE TITLE
Give proper folder structure

### ISSUE THREAD

**Issue by Julias0** [Julias0/sobdo#1]
All of the code is spread out inside the repo. Need a proper folder structure to make it easier for developers to navigate the codebase

Sample solution - 
```
.
|-- .github
|-- libs (this should be loaded from node_modules. But till we get a build system)
|-- src
|   |-- contentscripts
|   |   |-- css
|   |   `-- js
|   |-- popup
|   |   |-- html
|   |   |-- js
|   |   `-- css
|   |-- manifest.json
|   `-- icon.png
|-- package.json
|-- package-lock.json
|-- README.md
|-- CONTRIBUTING.md
`-- code-of-conduct.md

```

Haven't considered alternatives but feel free to propose

**Comment by subrat611** [comment]
Hi, @Julias0 I want to contribute to this issue. could you please assign this to me?

Here is my proposed solution based on your sample solution.

```
|-- .github
|   |-- ISSUE_TEMPLATE
|-- assets
|-- |-- screenshot.png
|-- libs
|-- src
|   |-- contentscripts
|   |   |-- css
|   |   |   |-- hint.min.css
|   |   |-- js
|   |       |-- content.js
|   |-- popup
|   |   |-- html
|   |   |   |-- popup.html
|   |   |-- js
|   |   |   |-- popup.js
|   |   `-- css
|   |       |-- styles.css
|   |-- bootstrap.min.css
|   |-- icon.png
|   |-- manifest.json
|-- package.json
|-- README.md
|-- CONTRIBUTING.md
|-- code-of-conduct.md
`-- .gitignore

```

**Comment by Julias0** [comment]
@subrat611 this is done. Let me know if you need any help!

**Comment by Julias0** [comment]
The bootstrap min css can you move inside the popup folder since it's only used there

**Comment by subrat611** [comment]
Sure I will do this. I have already done this task just checking if everything works properly.
